### ISSUE TITLE
Type Definition

### ISSUE THREAD

**Issue by hydrotik** [ldesplat/react-picture#4]
Any plans for a Type Definition to use with Typescript? I tried pulling in index.d.ts and no luck.

**Comment by ldesplat** [comment]
If you want to contribute it, I would most welcome it. I don't develop in typescript or flow, though I have seen how great it can be.

**Comment by hydrotik** [comment]
Sure no problem, currently I am using:

``` javascript
// Type definitions for React Picture v0.0.4
// Project: https://github.com/ldesplat/react-picture
// Definitions by: Donovan Adams <https://github.com/hydrotik>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

/// <reference path="./../react/react.d.ts" />

declare module ReactPicture {

    export var Image: any;

    export var BaseImage: any;
}

declare module "react-picture" {
    export = ReactPicture;
}
```

When I am able to tighten it up a bit I can drop you a note before submitting to TSD
